# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

stages:
- stage: tf_deploy
  displayName: "Terraform deploy"
  jobs:
  - job: initialize
    displayName: "Installing Terraformcommand"
    steps:
    - script: | 
          sudo apt-get update
          sudo apt-get install -y unzip
          sudo apt-get install -y wget
          wget https://releases.hashicorp.com/terraform/1.9.4/terraform_1.9.4_linux_amd64.zip
          unzip terraform_1.9.4_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version